version: "3.5"

networks:
    final_project:
        driver: bridge

services:
    redis:
        image: redis
        networks:
            - final
    flask:
        image: rylagan091888/final:latest
        command: "api.py"
        ports:
            - "5000:5000"
        environment:
            REDIS_IP: "redis"
        networks:
            - final
    worker:
        image: rylagan091888/final:latest
        command: "worker.py"
        environment:
            REDIS_IP: "redis"
        networks:
            - final