---
version: '3'
services:
    redis:
        image: rylagan091888/final:latest
        container_name: rylagan-db
        ports:
            - 6420:6379
        user: "827385:815499"
        volumes:
            - ../data/:/data/
    flask:
        image: rylagan091888/final:latest
        container_name: rylagan-api
        environment:
            - REDIS_IP=rylagan-db
        ports:
            - 5040:5000
    worker:
        image: rylagan091888/final:latest
        container_name: final-worker
        environment:
            - REDIS_IP=rylagan-db