FROM python:3.6.13

RUN ln -sf /usr/share/zoneinfo/America/Chicago /etc/localtime

RUN pip3 install Flask==1.1.2 \
                 hotqueue==0.2.8 \
                 pytest==6.2.3 \
                 redis==3.5.3 \
                 requests==2.25.1 \
		 matplotlib===3.3.4

COPY ./src/api.py /app/
COPY ./src/jobs.py /app/
COPY ./src/data.json /app/

WORKDIR /app

CMD ["python", "/app/api.py"]