---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rylagan-final-worker-deployment
  labels:
    app: rylagan-final-worker
    username: rylagan
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rylagan-final-worker
  template:
    metadata:
      labels:
        app: rylagan-final-worker
        username: rylagan
    spec:
      containers:
        - name: rylagan-final-worker
          imagePullPolicy: Always
          image: rylagan091888/final-wrk:latest
          #command: ['sleep', '999999999']
          env:
            - name: WORKER_IP
              value: "worker.py"