---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rylagan-final-worker-deployment
  labels:
    app: rylagan-final-worker
    username: rylagan
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rylagan-final-worker
  template:
    metadata:
      labels:
        app: rylagan-final-worker
        username: rylagan
        env: test
    spec:
      containers:
        - name: rylagan-final-worker
          image: rylagan091888/final:latest
          command: ["python", "worker.py"]
          ports:
            - name: flask
              containerPort: 5000
          env:
            - name: RD_HOST
              value: "10.109.76.73"
            - name: WORKER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP