---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rylagan-final-flask-deployment
  labels:
    app: rylagan-final-flask
    username: rylagan
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rylagan-final-flask
  template:
    metadata:
      labels:
        app: rylagan-final-flask
        env: test
    spec:
      containers:
        - name: rylagan-final-flask
          image: rylagan091888/final:latest
          imagePullPolicy: Always
          command: ["python", "api.py"]
          env:
            - name: REDIS_IP
              value: 10.106.251.26
          ports:
            - name: flask
              containerPort: 5000