---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rylagan-final-flask-deployment
  labels:
    app: rylagan-final-flask
    username: rylagan
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rylagan-final-flask
  template:
    metadata:
      labels:
        app: rylagan-final-flask
        env: test
    spec:
      containers:
        - name: rylagan-final-flask
          image: rylagan091888/final-api:latest
          imagePullPolicy: Always
          #command: ['sleep', '999999999']
          command: ["python", "api.py"]

          env:
            - name: FLASK_APP
              value: "api.py"
          ports:
            - name: http
              containerPort: 5000