---
apiVersion: v1
kind: Service
metadata:
  name: rylagan-test-redis-service
  labels:
    username: rylagan
    env: test
spec:
  type: ClusterIP
  selector:
    username: rylagan
    env: test
    app: rylagan-test-redis
  ports:
  - name: rylagan-test-redis
    port: 6379
    targetPort: 6379