version: '3'
services:
 web:
  build: .
  container_name: rry229-web
  ports:
   - 5040:5000

 redis:
  image: redis:latest
  ports:
   - 6420:6379
  volumes:
   - ./config/redis.conf:/redis.conf
  command: ["redis-server", "/redis.conf" ]