---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rylagan-test-flask-deployment
  labels:
    app: rylagan-test-flask
    username: rylagan
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rylagan-test-flask
  template:
    metadata:
      labels:
        app: rylagan-test-flask
        username: rylagan
        env: test
    spec:
      containers:
        - name: rylagan-test-flask
          imagePullPolicy: Always
          image: rylagan229/coe332-animals:1.0 
          ports:
            - name: flask
              containerPort: 5000
          env:
            - name: "RD_HOST"
              value: "10.109.76.73"