---
apiVersion: v1
kind: Service
metadata:
  name: rylagan-final-redis-service
  labels:
    username: rylagan
    env: final
spec:
  type: ClusterIP
  selector:
    app: rylagan-final-redis
  ports:
  - name: rylagan-final-redis
    port: 6379
    targetPort: 6379