---
apiVersion: v1
kind: Service
metadata:
  name: rylagan-test-flask-service
  labels:
    username: rylagan
    env: test
spec:
  type: ClusterIP
  selector:
    username: rylagan
    env: test
    app: rylagan-test-flask
  ports:
  - name: flask
    port: 5000
    targetPort: 5000